# Generated by Django 4.2.7 on 2023-11-19 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiatCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.PositiveBigIntegerField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyExchangeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crypto_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cryptocurrency')),
                ('fiat_currency', models.ManyToManyField(to='app.fiatcurrency')),
            ],
        ),
    ]
