# Generated by Django 4.2.7 on 2023-11-19 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_fiatcurrency_price_currencyexchangeinfo_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyexchangeinfo',
            name='fiat_currency',
        ),
        migrations.AddField(
            model_name='currencyexchangeinfo',
            name='fiat_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.fiatcurrency'),
            preserve_default=False,
        ),
    ]
