# Generated by Django 4.2.7 on 2023-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_currencyexchangeinfo_fiat_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyexchangeinfo',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
